export type CareerStats = {
  enemy_kills: number;
  terminid_kills: number;
  automaton_kills: number;
  friendly_kills: number;
  grenade_kills: number;
  melee_kills: number;
  eagle_kills: number;
  deaths: number;
  shots_fired: number;
  shots_hit: number;
  orbitals_used: number;
  defensive_stratagems_used: number;
  eagle_stratagems_used: number;
  supply_stratagems_used: number;
  reinforce_stratagems_used: number;
  total_stratagems_used: number;
  successful_extractions: number;
  objectives_completed: number;
  missions_played: number;
  missions_won: number;
  in_mission_time: string;
  samples_collected: number;
  total_xp_earned: number;
}; 